from pydantic import BaseModel, Field

class RequestModel(BaseModel):
    query: str = Field(..., description="The query to be processed by the model")

class ResponseModel(BaseModel):
    response: str = Field(..., description="The answer generated by the model")

